development:
  adapter: postgresql
  encoding: utf8
  database: datatrash_development
  pool: 5
  username: afsmnghr
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: datatrash_test
  pool: 5
  username: afsmnghr
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: datatrash_production
  pool: 5
  username: afsmnghr
  password: 
